version: '3.3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    ports:
      - "8082:3306"
  website:
    container_name: php73
    build:
      context: ./
    volumes:
      - ./websandbox:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
